version: '3'

services:
  drachtio-fsmrf-build:
    build:
      context: .
    restart: unless-stopped
    container_name: drachtio-fsmrf-build
    ports:
      - "5061:5061"
      - "8080:80"
      - "8443:443"
      - "2022:22"
    environment:
      - TRUNK_TYPE
      - TRUNK_ACCOUNT
      - TRUNK_PASSWORD
      - ARI_USER
      - ARI_PASSWORD
      - ARI_APPLICATION
